### ISSUE TITLE
Question for efficient-spiking-networks

### ISSUE THREAD

**Issue by kimh2144** [byin-cwi/Efficient-spiking-networks#2]
Hello, my name is Munhyeon Kim and I am Ph.D student at Seoul National University.

I found the article "Accurate and efficient time-domain classification with adaptive spiking recurrent neural networks" published in the journal Nature Machine Intelligence to be quite intriguing, and I thoroughly appreciated it. I appreciate your publication of a high-quality study.

I'd want to view the code on github and attempt to replicate it. While attempting to simulate an efficient neural network using the S-MNIST dataset, I discovered that the "trainer.py" file did not exist. Could you kindly send me the file?

I appreciate your cooperation in advance.

**Comment by byin-cwi** [comment]
Thanks for your interests Kim. I just back from holidays. You can check the code in https://github.com/byin-cwi/SRNN-ICONs2020/blob/master/s_mnist-gpu.py
